export const DAILY_QUOTES = [
  { quote: "Become who you are, even if the world resists it.", author: "Stoic / Nietzschean" },
  { quote: "Strength grows where comfort dies.", author: "Stoic / Nietzschean" },
  { quote: "Discipline is the quiet architect of victory.", author: "Stoic / Nietzschean" },
  { quote: "Suffering is raw iron; willpower is the forge.", author: "Stoic / Nietzschean" },
  { quote: "Do not beg life for ease. Command it with effort.", author: "Stoic / Nietzschean" },
  { quote: "The brave build meaning where others see chaos.", author: "Stoic / Nietzschean" },
  { quote: "Rise above resentment; climb toward power.", author: "Stoic / Nietzschean" },
  { quote: "The path of greatness is paved with solitude.", author: "Stoic / Nietzschean" },
  { quote: "A strong spirit turns wounds into weapons.", author: "Stoic / Nietzschean" },
  { quote: "What you endure today becomes your armor tomorrow.", author: "Stoic / Nietzschean" },
  { quote: "Greatness requires the courage to stand apart.", author: "Stoic / Nietzschean" },
  { quote: "Do not fear struggle; fear stagnation.", author: "Stoic / Nietzschean" },
  { quote: "Your destiny belongs to those who persist.", author: "Stoic / Nietzschean" },
  { quote: "The disciplined mind defeats chaos.", author: "Stoic / Nietzschean" },
  { quote: "Power begins where excuses end.", author: "Stoic / Nietzschean" },
  { quote: "Hard roads shape unbreakable spirits.", author: "Stoic / Nietzschean" },
  { quote: "Conquer yourself before conquering the world.", author: "Stoic / Nietzschean" },
  { quote: "Victory favors the relentless.", author: "Stoic / Nietzschean" },
  { quote: "Pain is the teacher of the determined.", author: "Stoic / Nietzschean" },
  { quote: "Stand firm even when misunderstood.", author: "Stoic / Nietzschean" },
  { quote: "Build the self you respect.", author: "Stoic / Nietzschean" },
  { quote: "Do not wait for permission to become powerful.", author: "Stoic / Nietzschean" },
  { quote: "Every hardship sharpens the will.", author: "Stoic / Nietzschean" },
  { quote: "The quiet warrior wins through discipline.", author: "Stoic / Nietzschean" },
  { quote: "Endure. Improve. Repeat.", author: "Stoic / Nietzschean" },
  { quote: "Character is forged in resistance.", author: "Stoic / Nietzschean" },
  { quote: "Let your actions argue for your greatness.", author: "Stoic / Nietzschean" },
  { quote: "Self-mastery is the highest victory.", author: "Stoic / Nietzschean" },
  { quote: "The strong write their own meaning.", author: "Stoic / Nietzschean" },
  { quote: "Do not chase comfort; chase excellence.", author: "Stoic / Nietzschean" },
  { quote: "Your future bows to your discipline.", author: "Stoic / Nietzschean" },
  { quote: "Silence doubt through action.", author: "Stoic / Nietzschean" },
  { quote: "Stand tall when others shrink.", author: "Stoic / Nietzschean" },
  { quote: "Endurance outlasts talent.", author: "Stoic / Nietzschean" },
  { quote: "Forge courage in the fire of adversity.", author: "Stoic / Nietzschean" },
  { quote: "The bold transform suffering into power.", author: "Stoic / Nietzschean" },
  { quote: "The strong mind commands the body.", author: "Stoic / Nietzschean" },
  { quote: "Destiny bends toward the persistent.", author: "Stoic / Nietzschean" },
  { quote: "Rise stronger after every fall.", author: "Stoic / Nietzschean" },
  { quote: "Discipline makes freedom possible.", author: "Stoic / Nietzschean" },
  { quote: "The wise build strength quietly.", author: "Stoic / Nietzschean" },
  { quote: "Pain is temporary; character is permanent.", author: "Stoic / Nietzschean" },
  { quote: "Strength grows in difficult seasons.", author: "Stoic / Nietzschean" },
  { quote: "The relentless shape the future.", author: "Stoic / Nietzschean" },
  { quote: "A powerful mind fears no challenge.", author: "Stoic / Nietzschean" },
  { quote: "Endure hardship with dignity.", author: "Stoic / Nietzschean" },
  { quote: "Victory belongs to the steadfast.", author: "Stoic / Nietzschean" },
  { quote: "Rise above weakness through effort.", author: "Stoic / Nietzschean" },
  { quote: "Master your impulses, master your life.", author: "Stoic / Nietzschean" },
  { quote: "The determined turn obstacles into ladders.", author: "Stoic / Nietzschean" },
  { quote: "Strength respects no excuses.", author: "Stoic / Nietzschean" },
  { quote: "Hard work is the language of ambition.", author: "Stoic / Nietzschean" },
  { quote: "Face adversity with calm resolve.", author: "Stoic / Nietzschean" },
  { quote: "The disciplined spirit cannot be broken.", author: "Stoic / Nietzschean" },
  { quote: "Great souls welcome great challenges.", author: "Stoic / Nietzschean" },
  { quote: "Rise each day stronger than before.", author: "Stoic / Nietzschean" },
  { quote: "Self-respect begins with self-control.", author: "Stoic / Nietzschean" },
  { quote: "Strength is earned, never granted.", author: "Stoic / Nietzschean" },
  { quote: "Let hardship sculpt your character.", author: "Stoic / Nietzschean" },
  { quote: "Those who endure ultimately lead.", author: "Stoic / Nietzschean" },
  { quote: "Stand firm against the storm.", author: "Stoic / Nietzschean" },
  { quote: "Excellence grows from daily effort.", author: "Stoic / Nietzschean" },
  { quote: "The strong refuse to surrender.", author: "Stoic / Nietzschean" },
  { quote: "Master difficulty through patience.", author: "Stoic / Nietzschean" },
  { quote: "Power grows in silent persistence.", author: "Stoic / Nietzschean" },
  { quote: "Do not complain-improve.", author: "Stoic / Nietzschean" },
  { quote: "Strength respects the disciplined.", author: "Stoic / Nietzschean" },
  { quote: "A resilient spirit conquers fate.", author: "Stoic / Nietzschean" },
  { quote: "Purpose turns pain into progress.", author: "Stoic / Nietzschean" },
  { quote: "Every trial prepares you for victory.", author: "Stoic / Nietzschean" },
  { quote: "Control the mind and you control the battle.", author: "Stoic / Nietzschean" },
  { quote: "Resolve outlasts fear.", author: "Stoic / Nietzschean" },
  { quote: "The determined transform struggle into strength.", author: "Stoic / Nietzschean" },
  { quote: "Stand proud of your discipline.", author: "Stoic / Nietzschean" },
  { quote: "The unbreakable are shaped by hardship.", author: "Stoic / Nietzschean" },
  { quote: "Action silences uncertainty.", author: "Stoic / Nietzschean" },
  { quote: "A calm mind defeats chaos.", author: "Stoic / Nietzschean" },
  { quote: "Climb beyond your former self.", author: "Stoic / Nietzschean" },
  { quote: "The bold walk paths others fear.", author: "Stoic / Nietzschean" },
  { quote: "Great spirits welcome resistance.", author: "Stoic / Nietzschean" },
  { quote: "Persistence transforms dreams into destiny.", author: "Stoic / Nietzschean" },
  { quote: "Let courage guide your steps.", author: "Stoic / Nietzschean" },
  { quote: "Strength grows through disciplined repetition.", author: "Stoic / Nietzschean" },
  { quote: "Resilience is the mark of the powerful.", author: "Stoic / Nietzschean" },
  { quote: "Hard days build strong minds.", author: "Stoic / Nietzschean" },
  { quote: "The brave define their own path.", author: "Stoic / Nietzschean" },
  { quote: "Conquer doubt through action.", author: "Stoic / Nietzschean" },
  { quote: "Your will decides your limits.", author: "Stoic / Nietzschean" },
  { quote: "Courage thrives under pressure.", author: "Stoic / Nietzschean" },
  { quote: "Strength begins with responsibility.", author: "Stoic / Nietzschean" },
  { quote: "Rise through effort, not excuses.", author: "Stoic / Nietzschean" },
  { quote: "Resolve outshines comfort.", author: "Stoic / Nietzschean" },
  { quote: "Greatness belongs to the relentless.", author: "Stoic / Nietzschean" },
  { quote: "Endure today to command tomorrow.", author: "Stoic / Nietzschean" },
  { quote: "The disciplined spirit rises above fate.", author: "Stoic / Nietzschean" },
  { quote: "Victory favors the prepared mind.", author: "Stoic / Nietzschean" },
  { quote: "Strength is built one struggle at a time.", author: "Stoic / Nietzschean" },
  { quote: "Walk boldly toward your destiny.", author: "Stoic / Nietzschean" }
]

export function getQuoteOfTheDay(date = new Date()) {
  const year = date.getFullYear()
  const month = date.getMonth()
  const day = date.getDate()
  const dayNumber = Math.floor(Date.UTC(year, month, day) / 86400000)
  const quoteIndex = ((dayNumber % DAILY_QUOTES.length) + DAILY_QUOTES.length) % DAILY_QUOTES.length

  return DAILY_QUOTES[quoteIndex]
}
